//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankingmachine
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int history_id { get; set; }
        public Nullable<int> users_id { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string type { get; set; }
    
        public virtual user user { get; set; }
    }
}
